### ISSUE TITLE
Translate the NSFW version to english

### ISSUE THREAD

**Issue by craviee** [jakubnabrdalik/gitkurwa#63]
Hello, I would like to create a PR adding the NSFW version in PT-BR (Portuguese-Brazil).
But first I need the version in english to make the translation.
It is possible to translate the NSFW to english?

**Comment by jakubnabrdalik** [comment]
Hi, sure.

Translating it to a language, that would make it funny (which was the point of NSFW versions - to help people learn / remember, by putting aliases in a language of an angry developer), requires not a direct word-for-word translation, but a creative writing IMHO.

So if I were to translate it to NSFW PT-BR version, I'd start with the SFW English version, which you have here https://github.com/jakubnabrdalik/gitkurwa/blob/master/config and then add the profanities according to the taste and the culture of the language group I'm targeting. 
Otherwise you could end up with something  offending, yet not funny.

That's my take on it. What do you think?
